WPHW6/Models/Quest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WPHW6.Models
{
    public class Quest
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }
        [Required(ErrorMessage ="name is required")]
        [MaxLength(50,ErrorMessage ="too long name")]
        [Display(Name="Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "description is required")]
        [MaxLength(500, ErrorMessage = "too long description")]
        [Display(Name = "Description")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Time is required")]
        [Display(Name = "Time")]
        public double Time { get; set; }
        [Required(ErrorMessage = "Min players is required")]
        [Display(Name = "Minimum players")]
        public int MinPlayers { get; set; }
        [Required(ErrorMessage = "Max players is required")]
        [Display(Name = "Maximum players")]
        public int MaxPlayers { get; set; }
        [Required(ErrorMessage = "Address is required")]
        [MaxLength(50, ErrorMessage = "too long address")]
        [Display(Name = "Address")]
        public string Address { get; set; }
        [MaxLength(20, ErrorMessage = "too long phone number")]
        [Display(Name = "Phone number")]
        public string Phone { get; set; }
        [MaxLength(50, ErrorMessage = "too long email")]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [MaxLength(50, ErrorMessage = "too long company name")]
        [Display(Name = "Company")]
        public string Company { get; set; }
        [Display(Name = "Rating")]
        [HiddenInput(DisplayValue = false)]
        public double Rating { get; set; }
        [Required(ErrorMessage = "FearLevel is required")]
        [Display(Name = "Fear level")]
        public double FearLevel { get; set; }
        [Required(ErrorMessage = "DifficultyLevel is required")]
        [Display(Name = "Difficulty level")]
        public double DifficultyLevel { get; set; }
        public string Logo { get; set; }
        public List<string> Gallery { get; set; }
    }
}

WPHW6/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WPHW6.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WPHW6/Controllers/QuestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WPHW6.Models;

namespace WPHW6.Controllers
{
    public class QuestsController : Controller
    {
        private IEnumerable<Quest> quests = new List<Quest>{
            new Quest() { Id=1,MaxPlayers = 5, MinPlayers = 1, FearLevel = 3, Email = "fear@gmail.com", DifficultyLevel = 3, Company = "Best quests inc", Address = "Pushki st. 34", Name = "AAAAA Strashno", Phone = "88005553535", Rating = 4.9, Time = 3.5, Description = "Long deeeeeeeeescription blablabla bla blablabla balbalbal balblabl", Logo= "https://images.unsplash.com/photo-1500602763988-7d6c9c1263ca?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=874&q=80", 
            Gallery=new List<string> { "https://images.unsplash.com/photo-1633555690973-b736f84f3c1b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80", "https://images.unsplash.com/photo-1635641398283-ee8f83a6e6f5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80" }
            },
            new Quest() {Id=2, MaxPlayers = 5, MinPlayers = 1, FearLevel = 3, Email = "fear@gmail.com", DifficultyLevel = 3, Company = "Best quests inc", Address = "Pushki st. 34", Name = "AAAAA Strashno", Phone = "88005553535", Rating = 4.9, Time = 3.5, Description = "Long deeeeeeeeescription blablabla bla blablabla balbalbal balblabl", Logo= "https://images.unsplash.com/photo-1500602763988-7d6c9c1263ca?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=874&q=80", 
            Gallery=new List<string> { "https://images.unsplash.com/photo-1633555690973-b736f84f3c1b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80", "https://images.unsplash.com/photo-1635641398283-ee8f83a6e6f5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80" }
            },
            new Quest() {Id=3, MaxPlayers = 5, MinPlayers = 1, FearLevel = 3, Email = "fear@gmail.com", DifficultyLevel = 3, Company = "Best quests inc", Address = "Pushki st. 34", Name = "AAAAA Strashno", Phone = "88005553535", Rating = 4.9, Time = 3.5, Description = "Long deeeeeeeeescription blablabla bla blablabla balbalbal balblabl", Logo= "https://images.unsplash.com/photo-1500602763988-7d6c9c1263ca?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=874&q=80", 
            Gallery=new List<string> { "https://images.unsplash.com/photo-1633555690973-b736f84f3c1b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80", "https://images.unsplash.com/photo-1635641398283-ee8f83a6e6f5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80" }
            }
        };
        // GET: Quests
        public ActionResult Index()
        {
            return View(quests);
        }
        public ActionResult AdminPanel()
        {
            return View(quests);
        }

        public ActionResult DescriptionCard(int id)
        {
            Quest quest = quests.ElementAt(id);
            return View(quest);
        }

        // GET: Quests/Details/5
        public ActionResult Details(int id)
        {
            Quest quest = quests.ElementAt(id);
            return View(quest);
        }

        // GET: Quests/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Quests/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Quests/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Quests/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Quests/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Quests/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WPHW6/Views/Quests/AdminPanel.cshtml
@model IEnumerable<WPHW6.Models.Quest>

@{
    ViewBag.Title = "AdminPanel";
}

<h2>AdminPanel</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MinPlayers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaxPlayers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Company)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FearLevel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DifficultyLevel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Logo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MinPlayers)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaxPlayers)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Company)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FearLevel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DifficultyLevel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Logo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

WPHW6/Views/Quests/Create.cshtml
@model WPHW6.Models.Quest

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Quest</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinPlayers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinPlayers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinPlayers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxPlayers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxPlayers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxPlayers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FearLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FearLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FearLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DifficultyLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DifficultyLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DifficultyLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WPHW6/Views/Quests/DescriptionCard.cshtml
@model WPHW6.Models.Quest

<div class="card" style="width: 18rem;">
    <img class="card-img-top" style="max-height:35%;width:100%" src="@Model.Logo" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">@Model.Description</p>
        @Html.ActionLink("details", "Details", "Quests", new { Model.Id }, new {@class= "btn btn-primary" })
    </div>
</div>

WPHW6/Views/Quests/Details.cshtml
@model WPHW6.Models.Quest

@{
    ViewBag.Title = "Details";
}
<div class="container">
    <div class="col-md-12" style="background-image:url(@Model.Logo); text-align:center; height:40vh;">
        <h1 style="color:white;">@Model.Name</h1>
    </div>
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-3">
                <h2>Gallery</h2>
                <div class="row">
                    @foreach (var pic in Model.Gallery)
                    {
                        <div class="col-md-6" style="max-height:20vh">
                            <img src="@pic" style="max-width:100%; max-height:100%" />
                        </div>
                    }
                </div>
            </div>
            <div class="col-md-4">
                <h2>Description</h2>
                <p>@Model.Description</p>
            </div>
            <div class="col-md-3" style="padding:15px; font-size:24px">
                <table>
                    <tr>
                        <td>Time:</td>
                        <td>@Model.Time hours</td>
                    </tr>
                    <tr>
                        <td>Players:</td>
                        <td>@Model.MinPlayers-@Model.MaxPlayers</td>
                    </tr>
                    <tr>
                        <td>Address:</td>
                        <td>@Model.Address</td>
                    </tr>
                    <tr>
                        <td>Phone:</td>
                        <td>@Model.Phone</td>
                    </tr>
                    <tr>
                        <td>Email:</td>
                        <td>@Model.Email</td>
                    </tr>
                    <tr>
                        <td>Company:</td>
                        <td>@Model.Company</td>
                    </tr>
                    <tr>
                        <td>Rating:</td>
                        <td>@Model.Rating%</td>
                    </tr>
                    <tr>
                        <td>Fear level:</td>
                        <td>@Model.FearLevel/5</td>
                    </tr>
                    <tr>
                        <td>Difficult level:</td>
                        <td>@Model.DifficultyLevel/5</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-1"></div>
        </div>
</div>

WPHW6/Views/Quests/Edit.cshtml
@model WPHW6.Models.Quest

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Quest</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinPlayers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinPlayers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinPlayers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxPlayers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxPlayers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxPlayers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Company, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FearLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FearLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FearLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DifficultyLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DifficultyLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DifficultyLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WPHW6/Views/Quests/Index.cshtml
@model IEnumerable<WPHW6.Models.Quest>

@{
    ViewBag.Title = "Index";
}

<h2>Quests</h2>
<div class="container">
    <div class="row">
        @foreach (var quest in Model)
        {
            <div class="col-md-2">
                @Html.Partial("DescriptionCard", quest)
            </div>
        }
    </div>
</div>