Exam1/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Exam1.Models;
using Exam1.Filters;
using Microsoft.AspNet.Identity;

namespace Exam1.Controllers
{
    public class AdminController : Controller
    {
        private AccountDBContext db = new AccountDBContext();

        // GET: Admin
        [AdminAuthentificationFilter]
        public async Task<ActionResult> AccountIndex()
        {
            return View(await db.Accounts.ToListAsync());
        }

        // GET: Admin/Details/5
        [AdminAuthentificationFilter]
        public async Task<ActionResult> AccountDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = await db.Accounts.FindAsync(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // GET: Admin/Create
        [AdminAuthentificationFilter]
        public ActionResult AccountCreate()
        {
            return View();
        }

        // POST: Admin/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminAuthentificationFilter]
        public async Task<ActionResult> AccountCreate([Bind(Include = "Id,Username,Password,AccountType")] Account account)
        {
            if (ModelState.IsValid)
            {
                PasswordHasher ph = new PasswordHasher();
                account.Password = ph.HashPassword(account.Password);
                db.Accounts.Add(account);
                await db.SaveChangesAsync();
                return RedirectToAction("AccountIndex");
            }

            return View(account);
        }

        // GET: Admin/Edit/5
        [AdminAuthentificationFilter]
        public async Task<ActionResult> AccountEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = await db.Accounts.FindAsync(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // POST: Admin/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminAuthentificationFilter]
        public async Task<ActionResult> AccountEdit([Bind(Include = "Id,Username,Password,AccountType")] Account account)
        {
            if (ModelState.IsValid)
            {
                PasswordHasher ph = new PasswordHasher();
                account.Password = ph.HashPassword(account.Password);
                db.Entry(account).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("AccountIndex");
            }
            return View(account);
        }

        // GET: Admin/Delete/5
        [AdminAuthentificationFilter]
        public async Task<ActionResult> AccountDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = await db.Accounts.FindAsync(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AdminAuthentificationFilter]
        public async Task<ActionResult> AccountDeleteConfirmed(int id)
        {
            Account account = await db.Accounts.FindAsync(id);
            db.Accounts.Remove(account);
            await db.SaveChangesAsync();
            return RedirectToAction("AccountIndex");
        }
        [AdminAuthentificationFilter]
        public async Task<ActionResult> ProductIndex()
        {
            return View(await db.ProductInfos.ToListAsync());
        }
        [AdminAuthentificationFilter]

        // GET: ProductInfoes/Details/5
        public async Task<ActionResult> ProductDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductInfo productInfo = await db.ProductInfos.FindAsync(id);
            if (productInfo == null)
            {
                return HttpNotFound();
            }
            return View(productInfo);
        }
        [AdminAuthentificationFilter]

        // GET: ProductInfoes/Create
        public ActionResult ProductCreate()
        {
            return View();
        }

        [AdminAuthentificationFilter]
        // POST: ProductInfoes/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ProductCreate([Bind(Include = "Id,Name,Description,Category,Photo,Price,TotalAmount,IsAuction")] ProductInfo productInfo)
        {
            if (ModelState.IsValid)
            {
                db.ProductInfos.Add(productInfo);
                await db.SaveChangesAsync();
                return RedirectToAction("ProductIndex");
            }

            return View(productInfo);
        }

        // GET: ProductInfoes/Edit/5
        [AdminAuthentificationFilter]
        public async Task<ActionResult> ProductEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductInfo productInfo = await db.ProductInfos.FindAsync(id);
            if (productInfo == null)
            {
                return HttpNotFound();
            }
            return View(productInfo);
        }

        // POST: ProductInfoes/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminAuthentificationFilter]
        public async Task<ActionResult> ProductEdit([Bind(Include = "Id,Name,Description,Category,Photo,Price,TotalAmount,IsAuction")] ProductInfo productInfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productInfo).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("ProductIndex");
            }
            return View(productInfo);
        }

        // GET: ProductInfoes/Delete/5
        [AdminAuthentificationFilter]
        public async Task<ActionResult> ProductDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductInfo productInfo = await db.ProductInfos.FindAsync(id);
            if (productInfo == null)
            {
                return HttpNotFound();
            }
            return View(productInfo);
        }

        // POST: ProductInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AdminAuthentificationFilter]
        public async Task<ActionResult> ProductDeleteConfirmed(int id)
        {
            ProductInfo productInfo = await db.ProductInfos.FindAsync(id);
            db.ProductInfos.Remove(productInfo);
            await db.SaveChangesAsync();
            return RedirectToAction("ProductIndex");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Exam1/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Exam1.Models;
using Microsoft.AspNet.Identity;

namespace Exam1.Controllers
{
    public class RegistrationController : Controller
    {
        private AccountDBContext db = new AccountDBContext();
        // GET: Accounts
        private Account RegistratedAccount()
        {
            try
            {
                return db.Accounts.Where(
                a => a.Sessions.Where(
                    s => s.Ip == HttpContext.Request.UserHostAddress).Where(s => s.EndTime > DateTime.UtcNow).Any()).Single();
            }
            catch (Exception)
            {
                return null;
            }
        }
        private List<Account> RegistratedAccounts()
        {
            return db.Accounts.Where(
                a => a.Sessions.Where(
                    s => s.Ip == HttpContext.Request.UserHostAddress).Where(s => s.EndTime > DateTime.UtcNow).Any()).ToList();
        }
        private void FixRegistration()
        {
            List<Account> accounts = RegistratedAccounts();
            foreach (var account in accounts)
            {
                //var res = db.Sessions.Where(s => s.Ip == HttpContext.Request.UserHostAddress).Where(s => s.EndTime > DateTime.UtcNow);
                //db.Sessions.RemoveRange(res);
                foreach (var s in account.Sessions)
                {
                    s.EndTime = DateTime.UtcNow;
                }
            }
            db.SaveChanges();
        }
        public async Task<ActionResult> Index()
        {
            //List<Account> accounts = db.Accounts.Where(a => a.IsLocked == true).ToList();

            List<Account> accounts = RegistratedAccounts();
            if (accounts.Count == 1 /*&& accounts.First().Sessions.Where(s => s.Ip == HttpContext.Request.UserHostAddress).First().EndTime<DateTime.UtcNow*/)
            {
                Account account = accounts.First();
                AccountType type = account.AccountType;
                switch (type)
                {
                    case AccountType.Admin:
                        return RedirectToAction("AccountIndex","Admin");
                    case AccountType.Customer:
                        return RedirectToAction("Index","Customer");
                    default:
                        return RedirectToAction("SignIn");
                }
            }
            else if (accounts.Count == 0)
            {
                TempData["message"] = "please complete registration";
                return RedirectToAction("SignIn");
            }
            else
            {
                FixRegistration();
                TempData["message"] = "please complete registration";
                return RedirectToAction("SignIn");
            }
        }
        public async Task<ActionResult> SignIn()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> SignIn(Account account)
        {
            if (ModelState.IsValid)
            {
                List<Account> currentAccounts = db.Accounts.Where(a => (a.Username == account.Username)).ToList();
                if (currentAccounts.Count == 1)
                {
                    PasswordHasher ph = new PasswordHasher();
                    switch (ph.VerifyHashedPassword(currentAccounts.First().Password, account.Password))
                    {
                        case PasswordVerificationResult.Success:
                            {
                                Session session = new Session() { Account = currentAccounts.First(), StartTime = DateTime.UtcNow, EndTime = DateTime.UtcNow.AddHours(1), Ip = HttpContext.Request.UserHostAddress };
                                db.Sessions.Add(session);
                                currentAccounts.First().Sessions.Add(session);
                                db.SaveChanges();
                                return RedirectToAction("Index");
                            }
                        case PasswordVerificationResult.Failed:
                            {
                                TempData["message"] = "invalid password or username";
                                return RedirectToAction("SignIn");
                            }
                        case PasswordVerificationResult.SuccessRehashNeeded:
                            {
                                currentAccounts.First().Password = ph.HashPassword(account.Password);
                                Session session = new Session() { Account = currentAccounts.First(), StartTime = DateTime.UtcNow, EndTime = DateTime.UtcNow.AddHours(1), Ip = HttpContext.Request.UserHostAddress };
                                db.Sessions.Add(session);
                                currentAccounts.First().Sessions.Add(session);
                                db.SaveChanges();
                                return RedirectToAction("Index");
                            }


                    }

                }
                else
                {
                    TempData["message"] = "invalid password or username";
                    return RedirectToAction("SignIn");  
                }
            }
            return RedirectToAction("SignIn");
        }
        public async Task<ActionResult> SignUp()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> SignUp(Account account)
        {
            if (db.Accounts.Where(a => a.Username == account.Username).Count() == 0)
            {
                account.AccountType = AccountType.Customer;
                PasswordHasher ph = new PasswordHasher();
                account.Password = ph.HashPassword(account.Password);
                
                Session session = new Session() { Ip = HttpContext.Request.UserHostAddress, Account = account, StartTime = DateTime.UtcNow, EndTime = DateTime.UtcNow.AddHours(1) };
                db.Sessions.Add(session);
                db.Accounts.Add(account);
                account.Sessions.Add(session);
                
                db.SaveChanges();
            }
            else
            {
                TempData["message"] = "occupied username";
                return RedirectToAction("SignUp");
            }
            return RedirectToAction("Index");
        }
        public async Task<ActionResult> LogOut()
        {
            var res = db.Sessions.Where(s => s.Ip == HttpContext.Request.UserHostAddress).Where(s=>s.EndTime>DateTime.UtcNow);
            //db.Sessions.RemoveRange(res);
            foreach (var s in res)
            {
                s.EndTime = DateTime.UtcNow;
            }
            db.SaveChanges();
            return RedirectToAction("Index","Customer");
        }
    }
}

Exam1/Views/Shared/AdminsLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="Дополнительные параметры">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            <div class="navbar-brand">Market</div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accounts", "AccountIndex", "Admin")</li>
                    <li>@Html.ActionLink("Products", "ProductIndex", "Admin")</li>
                    <li>@Html.ActionLink("Log out", "LogOut", "Registration")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Exam1/Views/Shared/Unauthorized.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-fixed-top bg-nav">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="Дополнительные параметры">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Market", "Index", "Customer", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Log in", "SignIn", "Registration")</li>
                    <li>@Html.ActionLink("Sign up", "SignUp", "Registration")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="min-height: 78vh">
        @RenderBody()
    </div>

    <hr />
    <footer>
        <p style="padding:10px">&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Exam1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">*@
    <div class="navbar navbar-fixed-top bg-nav">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="Дополнительные параметры">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Market", "Index", "Customer", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse ">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Cabinet", "PersonalCabinet", "Customer")</li>*@
                    <li>
                        <a href='@Url.Action("PersonalCabinet", "Customer")'>
                            Cabinet&nbsp;<i class="bi bi-person-fill"></i>
                        </a>
                    </li>
                    @*<li>@Html.ActionLink("Basket", "Basket", "Customer")</li>*@
                    <li>
                        <a href='@Url.Action("Basket", "Customer")'>
                            Basket&nbsp;<i class="bi bi-basket-fill"></i>
                        </a>
                    </li>
                    @*<li>@Html.ActionLink("Log out", "LogOut", "Registration")</li>*@
                    <li>
                        <a href='@Url.Action("LogOut", "Registration")'>
                            Log out&nbsp;<i class="bi bi-box-arrow-right"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="min-height: 78vh">
        @RenderBody()

    </div>

    <hr />
    <footer>
        <nav class="navbar fixed-bottom navbar-light bg-light">
            <div class="container-fluid">
                <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
            </div>
        </nav>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>



</html>